# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EarthCalc
                                 A QGIS plugin
 This plugin calculates earthworks for PV trackers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-28
        copyright            : (C) 2024 by Marco Alvarez-Patino
        email                : malvarez-patino@revamp-eng.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load EarthCalc class from file EarthCalc.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .earth_calc import EarthCalc
    return EarthCalc(iface)
